### ISSUE TITLE
Infografia Gestión de proyectos de software 

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JazminloRI#2]
[Infografia_JazminLR.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JazminloRI/files/9420408/Infografia_JazminLR.pdf)

**Comment by Nayee123** [comment]
20/20 buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
